name: Go CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop
permissions:
  contents: read

jobs:
  # Lint the code
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.13'
          cache: true

      - name: Check formatting
        run: |
          files=$(gofmt -l .)
          if [ -n "$files" ]; then
            echo "gofmt errors in the following files:"
            echo "$files"
            exit 1
          fi
      - name: Go vet
        run: go vet ./...

  # Run tests
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.13'
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run race detector
        run: go test -race ./...

      - name: Run coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Show coverage
        run: go tool cover -func=coverage.out

  # Build the binary
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.13'
          cache: true

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd/server

      - name: Verify binary
        run:
          file app
          ls -lh app
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: app

  #Security scan
  security:
    name: Security
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.13'
          cache: true

      - name: Check vulnerabilities
        run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  #docker
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    needs:
      - test
      - security

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get lowercase image name
        id: image
        run: |
          echo "name=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image.outputs.name }}:${{ github.sha }}
            ${{ steps.image.outputs.name }}:latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: Deploy
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$VPS_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts

          # GHCR requires lowercase owner/repo
          GITHUB_USERNAME=$(echo "$GITHUB_USERNAME" | tr '[:upper:]' '[:lower:]')

          ssh "$VPS_USER@$VPS_HOST" "
            cd /cicd-test &&
            export GITHUB_USERNAME=$GITHUB_USERNAME &&
            export IMAGE_TAG=$IMAGE_TAG &&
            docker compose pull &&
            docker compose up -d &&
            docker image prune -f
          "

  #final
  final:
    name: Final
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test
      - build
      - security
      - docker

    steps:
      - name: CI passed
        run: echo "CI passed"